#!/bin/bash

cd "$(dirname "$0")"


 echo "Barcode eingabe"
 echo "A/a Barcode nicht bekannt"
 read antwort

if [ $antwort = a -o $antwort = A ];
 then
  echo "Was für Essen? Sorte oder Marke eingeben"
  echo "A/a für gesammte Datenbank"
  read lab
   if [ $lab = A -o $lab = a ];
    then
      echo "select Marke, Sorte, Barcode from Produkte;" | sqlite3 Datenbank/SQL
      echo "Barcode eingabe"
      read antwort
   else
    echo "select * from Produkte where Sorte like \"$lab\" or Marke like \"$lab\";" | sqlite3 Datenbank/SQL
    echo "Barcode eingabe"
    read antwort
   fi
fi

if [ $(echo "select * from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL) ];
 then
  echo "Backofen B/b"
  echo "Microwelle M/m"
  echo "Abbrechen A/a"
  read antwort2
   if [ $antwort2 = A -o $antwort2 = a ];
    then
     exit 0
   fi
   if [ $antwort2 = M -o $antwort2 = m ];
    then 
     Zeit=$(echo "select Microwelle_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
   fi 
   if [ $antwort2 = B -o $antwort2 = b ];
    then
     echo "Umluft U/u"
     echo "Ober/Unterhitze O/o"
     read antwort1
     if [ $antwort1 = U -o $antwort1 = u ];
      then
       Zeit=$(echo "select Umluft_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
     elif [ $antwort1 = O -o $antwort1 = o];
      then
       Zeit=$(echo "select OUHitze_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
     fi
   fi 
   while [ $Zeit -ge 1 ];
    do
     clear
     echo "Noch $Zeit Minuten warten..."
     sleep 60
     Zeit=$[$Zeit-1]
   done
   echo "He Cheff esse isch fertig"
   /usr/bin/firefox -new-window http://192.168.178.33:8080/stream.html &
   cvlc --play-and-exit /home/kaeptnbalu/Schreibtisch/essen/musik/Pizza.mp3
   exit
fi

if [ -z $(echo "select * from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL) ];
 then
  echo "Neuer Datenbankeintrag?"
  echo "J/N"
  read erstellen
   if [ $erstellen = J -o $erstellen = j ];
    then
     echo "Backofen B/b Microwelle M/m"
     read BoderM
     if [ $BoderM = M -o $BoderM = m ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer"
       read Dauer
       if [ $Hinweis_gesetzt = J -o $Hinweis_gesetzt = j ];
        then
         echo "Hinweis eingeben"
         read Hinweis
         echo  "insert into Produkte ( Marke, Sorte, Sonstiges, Microwelle_Zeit,  Barcode )  values(  \"$marke\", \"$sorte\", \"$Hinweis\",$Dauer, $antwort);" | sqlite3 Datenbank/SQL
         echo "Eintrag $antwort angelegt"
       exit 0
       else
        echo "Hinweis wird nicht angelegt"
        echo  echo "insert into Produkte ( Marke, Sorte, Sonstiges, Microwelle_Zeit,  Barcode  )  values(  \"$marke\", \"$Hinweis\", $Dauer,$antwort);" | sqlite3 Datenbank/SQL
        echo "Eintrag $antwort angelegt"
        exit 0
       fi

     elif [ $BoderM = B -o $BoderM = b ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer Umluft"
       read Umluft
       echo "Dauer Ober/unterhitze"
       read OU
       echo "Hinweis hinzufügen?"
       echo J/N
       read Hinweis_gesetzt
       if [ $Hinweis_gesetzt = J -o $Hinweis_gesetzt = j ];
        then
         echo "Hinweis eingeben"
         read Hinweis
         echo "insert into Produkte ( Marke, Sorte, Sonstiges, Umluft_Zeit, OUHitze_Zeit, Barcode )  values(  \"$marke\", \"$sorte\", \"$Hinweis\",$Umluft ,$OU ,$antwort);" | sqlite3 Datenbank/SQL
         echo "Eintrag $antwort angelegt"
         exit 0
       elif [ $Hinweis_gesetzt = N -o $Hinweis_gesetzt = n ];
        then
        echo "insert into Produkte ( Marke, Sorte, Umluft_Zeit, OUHitze_Zeit, Barcode )  values(  \"$marke\", \"$Hinweis\",$Umluft ,$OU ,$antwort);" | sqlite3 Datenbank/SQL
        echo "Eintrag $antwort angelegt"

         exit 0
       else
        echo "Hinweis wird nicht angelegt"
        echo  echo "insert into Produkte ( Marke, Sorte, Umluft_Zeit, OUHitze_Zeit, Barcode )  values(  \"$marke\", \"$Hinweis\",$Umluft ,$OU ,$antwort);" | sqlite3 Datenbank/SQL
        echo "Eintrag $antwort angelegt"
        exit 0
       fi
     fi
   else
    exit 0
   fi
fi

