#!/bin/bash

cd "$(dirname "$0")"

error="[\033[0;31mERROR\033[0m]"
warning="[\033[1;33mWARNING\033[0m]"
ok="[\033[0;32mOK\033[0m]"

isNumeric='^[0-9]+$'

if ! [ -f Datenbank/SQL ];then
    echo -e "$error Datenbank ist nicht vorhanden"
fi

echo "Barcode eingabe"
echo "A/a Barcode nicht bekannt"
read barcode

if [ $barcode = a -o $barcode = A ];
 then
  echo "Was für Essen? Sorte oder Marke eingeben."
  echo "A/a für gesammte Datenbank"
  read lab

  if [ $lab = A -o $lab = a ];
   then
    results=$(echo "select * from Produkte;" | sqlite3 Datenbank/SQL)
  else
    results=$(echo "select * from Produkte where Sorte like \"$lab\" or Marke like \"$lab\";" | sqlite3 Datenbank/SQL)
  fi
  mapfile -t products <<< "$results"
  if [ ${products[0]} ];
   then
    for product in "${products[@]}"
    do
      echo $product
    done
    echo "Barcode eingabe"
    read antwort
  else
    echo -e "$warning Keinen Eintrag gefunden"
    exit 1
  fi
elif ! [[ $barcode =~ $isNumeric ]]
 then
  echo -e "$error Unbekanntes Barcode-Format"
  exit 1
fi

product=$(echo "select * from Produkte where Barcode = \"$barcode\";" | sqlite3 Datenbank/SQL)

if [ $product ];
 then
  echo "Backofen B/b"
  echo "Microwelle M/m"
  echo "Abbrechen A/a"
  read antwort2
   if [ $antwort2 = A -o $antwort2 = a ];
    then
     exit 0
   fi
   if [ $antwort2 = M -o $antwort2 = m ];
    then
     Zeit=$(echo "select Microwelle_Zeit from Produkte where Barcode = $barcode;" | sqlite3 Datenbank/SQL)
   fi
   if [ $antwort2 = B -o $antwort2 = b ];
    then
     echo "Umluft U/u"
     echo "Ober/Unterhitze O/o"
     read antwort1
     if [ $antwort1 = U -o $antwort1 = u ];
      then
       Zeit=$(echo "select Umluft_Zeit from Produkte where Barcode = $barcode;" | sqlite3 Datenbank/SQL)
     elif [ $antwort1 = O -o $antwort1 = o];
      then
       Zeit=$(echo "select OUHitze_Zeit from Produkte where Barcode = $barcode;" | sqlite3 Datenbank/SQL)
     fi
   fi
   while [ $Zeit -ge 1 ];
    do
     clear
     echo "Noch $Zeit Minuten warten..."
     sleep 60
     Zeit=$[$Zeit-1]
   done
   echo "He Cheff esse isch fertig"
   /usr/bin/firefox -new-window http://192.168.178.33:8080/stream.html &
   cvlc --play-and-exit /home/kaeptnbalu/Schreibtisch/essen/musik/Pizza.mp3
   exit 0
else
  echo "Neuer Datenbankeintrag?"
  echo "J/N"
  read erstellen
   if [ $erstellen = J -o $erstellen = j ];
    then
     echo "Backofen B/b Microwelle M/m"
     read BoderM
     if [ $BoderM = M -o $BoderM = m ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer"
       read Dauer
       if [ $Hinweis_gesetzt = J -o $Hinweis_gesetzt = j ];
        then
         echo "Hinweis eingeben"
         read Hinweis
         echo  "insert into Produkte ( Marke, Sorte, Sonstiges,
         Microwelle_Zeit,  Barcode )  values(  \"$marke\", \"$sorte\", \"$Hinweis\",$Dauer, $barcode);" | sqlite3 Datenbank/SQL
         echo "Eintrag $barcode angelegt"
       exit 0
       else
        echo "Hinweis wird nicht angelegt"
        echo  echo "insert into Produkte ( Marke, Sorte, Sonstiges,
        Microwelle_Zeit,  Barcode  )  values(  \"$marke\", \"$Hinweis\", $Dauer,$barcode);" | sqlite3 Datenbank/SQL
        echo "Eintrag $barcode angelegt"
        exit 0
       fi

     elif [ $BoderM = B -o $BoderM = b ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer Umluft"
       read Umluft
       echo "Dauer Ober/unterhitze"
       read OU
       echo "Hinweis hinzufügen?"
       echo J/N
       read Hinweis_gesetzt
       if [ $Hinweis_gesetzt = J -o $Hinweis_gesetzt = j ];
        then
         echo "Hinweis eingeben"
         read Hinweis
         echo "insert into Produkte ( Marke, Sorte, Sonstiges, Umluft_Zeit,
         OUHitze_Zeit, Barcode )  values(  \"$marke\", \"$sorte\", \"$Hinweis\",$Umluft ,$OU ,$barcode);" | sqlite3 Datenbank/SQL
         echo "Eintrag $barcode angelegt"
         exit 0
       elif [ $Hinweis_gesetzt = N -o $Hinweis_gesetzt = n ];
        then
        echo "insert into Produkte ( Marke, Sorte, Umluft_Zeit, OUHitze_Zeit,Barcode )  values(  \"$marke\", \"$Hinweis\",$Umluft ,$OU ,$barcode);" | sqlite3 Datenbank/SQL
        echo "Eintrag $barcode angelegt"

         exit 0
       else
        echo "Hinweis wird nicht angelegt"
        echo  echo "insert into Produkte ( Marke, Sorte, Umluft_Zeit,
        OUHitze_Zeit, Barcode )  values(  \"$marke\", \"$Hinweis\",$Umluft ,$OU,$barcode);" | sqlite3 Datenbank/SQL
        echo "Eintrag $barcode angelegt"
        exit 0
       fi
     fi
   else
    exit 0
   fi
fi

