#!/bin/bash

cd "$(dirname "$0")"


# jloehel was here

 echo "Barcode eingabe"
 echo "A/a Barcode nicht bekannt"
 read antwort

if [ $antwort = a -o $antwort = A ];
 then
  echo "Was für Essen? Sorte oder Marke eingeben"
  echo "A/a für gesammte Datenbank"
  read lab
   if [ $lab = A -o $lab = a ];
    then
      echo "select * from Produkte;" | sqlite3 Datenbank/SQL
      echo "Barcode eingabe"
      read antwort
   else
    echo "select * from Produkte where Sorte like \"$lab\" or Marke like \"$lab\";" | sqlite3 Datenbank/SQL
    echo "Barcode eingabe"
    read antwort
   fi
fi

if [ -n $(echo "select * from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL) ];
 then
  echo "Backofen B/b"
  echo "Microwelle M/m"
  echo "Abbrechen A/a"
  read antwort2
   if [ $antwort2 = A -o $antwort2 = a ];
    then
     exit 0
   fi
   if [ $antwort2 = M -o $antwort2 = m ];
    then 
     Zeit=$(echo "select Microwelle_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
   fi 
   if [ $antwort2 = B -o $antwort2 = b ];
    then
     echo "Umluft U/u"
     echo "Ober/Unterhitze O/o"
     read antwort1
     if [ $antwort1 = U -o $antwort1 = u ];
      then
       Zeit=$(echo "select Umluft_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
     elif [ $antwort1 = O -o $antwort1 = o];
      then
       Zeit=$(echo "select OUHitze_Zeit from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL)
     fi
   fi 
   while [ $Zeit -ge 1 ];
    do
     clear
     echo "Noch $Zeit Minuten warten..."
     sleep 60
     Zeit=$[$Zeit-1]
   done
   echo "He Cheff esse isch fertig"
   /usr/bin/firefox -new-window http://192.168.178.33:8080/stream.html &
   cvlc --play-and-exit /home/kaeptnbalu/Schreibtisch/essen/musik/Pizza.mp3
   exit
fi

if [ -z $(echo "select * from Produkte where Barcode = $antwort;" | sqlite3 Datenbank/SQL) ];
 then
  echo "Neuer Datenbankeintrag?"
  echo "J/N"
  read erstellen
   if [ $erstellen = J -o $erstellen = j ];
    then
     echo "Backofen B/b Microwelle M/m"
     read BoderM
     if [ $BoderM = M -o $BoderM = m ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer"
       read Dauer
       echo "insert into Produkte values($marke,$schinken, null , null , $Dauer, $antwort);" | SQLite3 Datenbank/SQL
       echo "Eintrag $antwort angelegt"
       exit 0
     elif [ $BoderM = B -o $BoderM = b ];
      then
       echo "Marke"
       read marke
       echo "Sorte"
       read sorte
       echo "Dauer Umluft"
       read Umluft
       echo "Dauer Ober/unterhitze"
       read OU
       echo "insert into Produkte values($marke,$schinken, $Umluft  , $OU  , null , $antwort);" | SQLite3 Datenbank/SQL
       echo "Eintrag $antwort angelegt"
       exit 0
     fi
   else
    exit 0
   fi
fi

